# Please read https://github.com/holtwick/briefing/blob/master/docs/docker.md for proper use of Docker

services:
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  express:
    image: docker.io/bitnami/express:4
    restart: always
    # expose:
    #   - 3000
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/myapp
      - EXPRESS_SKIP_DB_WAIT=0
      - EXPRESS_SKIP_DB_MIGRATION=0
      - EXPRESS_SKIP_NPM_INSTALL=0
      - EXPRESS_SKIP_BOWER_INSTALL=0
    volumes:
      - './express-src:/app'
    depends_on:
      - mongodb
    env_file:
      - ./.env
    command: './entry.sh'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meetapi-louislabs.rule=Host(`meetapi.louislabs.com`)"
      - "traefik.http.routers.meetapi-louislabs.entrypoints=web"
      - "traefik.http.services.meetapi-louislabs.loadbalancer.server.port=3000"

  briefing:
    # image: holtwick/briefing
    build: ./briefing-src-cust
    restart: always
    # ports:
    #   - 8080:8080
    env_file: .env
    working_dir: /app
    command: ./entry.sh
    # command: sleep infinity
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meet-louislabs-http.rule=Host(`meet.louislabs.com`)"
      - "traefik.http.routers.meet-louislabs-http.entrypoints=web"
      - "traefik.http.services.meet-louislabs-http.loadbalancer.server.port=8080"

    depends_on:
      - express

  # whoami-iamon99:
  #   image: 'traefik/whoami'
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.apple-iamon99-http.rule=Host(`apple.iamon99.com`)"
  #     - "traefik.http.routers.apple-iamon99-http.entrypoints=web"

  #     # NOTE: container serving 80 port
  #     - "traefik.http.services.apple-iamon99-http.loadbalancer.server.port=80"

networks:
  default:
    name: traefik-proxy-network
    external: true
