# Please read https://github.com/holtwick/briefing/blob/master/docs/docker.md for proper use of Docker

version: '3'

services:
  briefing:
    # image: holtwick/briefing
    build:
      context: .
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - 8888:8080
    command: ./entry.sh

networks:
  default:
    external:
      name: traefik-proxy-network
